# Generated by Django 4.2.10 on 2024-04-22 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_updated_on_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
